apps/grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
from django.conf.urls.defaults import *
from django.conf import settings


urlpatterns = patterns('',
    
    # FOREIGNKEY & GENERIC LOOKUP
    url(r'^lookup/related/$', 'grappelli.views.related.related_lookup', name="grp_related_lookup"),
    url(r'^lookup/m2m/$', 'grappelli.views.related.m2m_lookup', name="grp_m2m_lookup"),
    url(r'^lookup/autocomplete/$', 'grappelli.views.related.autocomplete_lookup', name="grp_autocomplete_lookup"),
    
)

urls.py
from django.conf.urls.defaults import patterns, include
from django.conf import settings
from django.views.generic.simple import direct_to_template
from apps.busca.models import Planta, Sequencia
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('busca.views',

    (r'^$', 'index'),
    (r'^plantas/$', 'pagina_especifica', {'entidade': Planta,
                                          'tipo': 'P',
                                          'template': 'busca/plantas.html'}),
    (r'^plantas/(?P<planta_id>\d+)/$', 'perfil_planta'),
    (r'^plantas/busca/(?P<busca>\S+.*)/$', 'resultado_plantas'),
    (r'^sequencias/$', 'pagina_especifica', {'entidade': Sequencia,
                                             'tipo': 'S',
                                             'template': 'busca/sequencias.html'}),
    (r'^sequencias/(?P<planta_id>\d+)/$', 'pagina_sequencias'),
    (r'^sequencias/(?P<planta_id>\d+)/(?P<sequencia_id>\d+)/$', 'perfil_sequencia'),
    (r'^sequencias/busca/(?P<busca>.*)/$', 'resultado_sequencias'),
    (r'^alinhamento/', 'alinhamento'),
	(r'^blast/','motifs'),
)


urlpatterns += patterns('',
	(r'^usuarios/$', 'usuarios.views.usuario'),
    (r'^usuarios/registrar/$', 'usuarios.views.registro_user'),
    (r'^usuarios/registrar/sucesso/$', direct_to_template, {'template': 'usuarios/registro_sucesso.html'}),
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'usuarios/login.html'}),
    (r'^usuarios/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
)


urlpatterns += patterns('contato.views',
    (r'^contato/$', 'contato'),
)


urlpatterns += patterns('',
    (r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    (r'^grappelli/', include('grappelli.urls')),
)

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG: # Problema com os downloads
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),)

apps/busca/forms.py
# coding: utf-8

from django import forms
from apps.busca.models import Planta, Sequencia


TIPOS = (('P', u'Organismo'),
         ('S', u'Sequência'))

class BlastForm(forms.Form):
	motif = forms.CharField(widget = forms.Textarea(), label = 'Blast')
    #filogenia = forms.FileField(label = 'Filogenia - Upload do alinhamento das sequências')
class AlinhamentoForm(forms.Form):
    sequencia_one = forms.CharField(label = u'Sequencia_Um',widget = forms.Textarea())
    sequencia_two = forms.CharField(label = u'Sequencia_Dois',widget = forms.Textarea())
    file_seq = forms.FileField(required=False)
    gap_extension = forms.CharField(label = u'Gap_Extension', initial = '0.2')
    gap_open = forms.CharField(label = u'Gap_Open_Penaly', initial = '10.0')
    gap_separation = forms.CharField(label = u'Gap_Separation_Distance', initial = '4')
    end_gap = forms.CharField(label = u'End_Gap', initial = '-1')


class BuscaForm(forms.Form):
    busca = forms.CharField()


class BuscaEscolhaForm(forms.Form):
    escolha = forms.ChoiceField(choices=TIPOS,widget=forms.Select(attrs={'class':'fancy'}))
    busca = forms.CharField(widget=forms.TextInput(attrs={'style':'width:450px;height:24px;'}))


class PlantaForm(forms.ModelForm):
    class Meta:
        model = Planta

    def clean_nome_cientifico(self):
        nome = self.cleaned_data['nome_cientifico']
        #if Planta.objects.filter(nome_cientifico=nome):
            #raise forms.ValidationError('O nome já existe no banco.')
        if len(nome.split()) < 2:
            raise forms.ValidationError('O nome deve seguir a nomenclatura binomial.')
        return nome
    
    #def clean_imagem(self):
        #img = self.cleaned_data['imagem']
        #if img._size > 104857:
         #   raise forms.ValidationError('Imagem muito grande! Insira uma imagem com, no máximo, 100KB.')
       # return img


class SequenciaForm(forms.ModelForm):
    class Meta:
        model = Sequencia

    def clean_titulo(self):
        titulo_ = self.cleaned_data['titulo']
        if Sequencia.objects.filter(titulo=titulo_):
            raise forms.ValidationError('O nome já existe no banco.')
        return titulo_

    def clean_arquivo(self):
        seq = self.cleaned_data['arquivo']
        extensao = seq.name.split('.')[-1]
        if extensao.lower() != 'fasta':
            raise forms.ValidationError('Insira um arquivo do tipo FASTA.')
        return seq

templates/alinhamento/alinhamento.html
{% extends 'busca/resul_planta.html' %}

{% block nome %}
	<p style="font-size:20px; color:green;">Alinhamento</p>	
{% endblock %}

{%block contato%}
<div id="pagina_conteudo">
<!--

	<form method="POST">	
		{% csrf_token %}
		{% for campo in form %}
			<div class="fieldWrapper">
				{% if campo.errors%}
					<div style="width:170px; height:20px; list-style:none;font-size:11.5px;" class="notice error">{{ campo.errors }}</div>		
				{% endif %}	
				{{ campo.label_tag }}:</br>
				{{ campo }}
			</div>
		{% endfor %}
		<button type="submit" style="margin-top:10px;">Enviar</button>	
	</form>-->

	
	<form method="POST">
		{% csrf_token %}
		<p><label for="id_sequencia_one" class="label_test">Sequencia_UM:</label></br>
    	<textarea id="id_sequencia_one" type="text" name="sequencia_one" style="height:120px; width:400px;"/></textarea></p>
    	<p><label for="id_sequencia_two" class="label_test">Sequencia_DOIS:</label></br>
    	<textarea id="id_sequencia_two" type="text" name="sequencia_two" style="height:120px; width:400px;"/></textarea></p>
    	<p><label for="id_file_seq" class="label_test">Upload_Arquivo:</label>
    		{{form.file_seq}}

    	<div id="form_ali">
    		<p style="font-size:20px;color:green;">Parametros</p>
    		<p><label for="id_gap_extension" class="label_test">Gap_Extensão:</label></br>
    			{{form.gap_extension}}
    		<p><label for="id_gap_open" class="label_test">Gap_Abertura_Penalidade:</label></br>
    			{{form.gap_open}}	
    		<p><label for="id_gap_separation" class="label_test">Gap_Separação_Distancia:</label></br>
    			{{form.gap_separation}}		
    		<p><label for="id_end_gap" class="label_test">Gap_Final:</label></br>
    			{{form.end_gap}}		
    	</div>
    	<button type="submit" style="margin-top:5px;">Enviar</button>
	</form>
	
</div>
{%endblock%}

templates/alinhamento/alinhamento_result.html
{% extends "busca/resul_seq.html" %}

{% block estilos_extra %}
	<script type="text/javascript" src="{{ STATIC_URL }}js/raphael-min.js" ></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jsphylosvg-min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/unitip/js/unitip.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}yui/build/yui/yui-min.js"></script>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}js/unitip/css/unitip.css" media="all" />
	
{% endblock %}

{% block java %}
	<script type="text/javascript">
	window.onload = function(){
    YUI().use('oop', 'json-stringify', 'io-base', 'event', 'event-delegate', function(Y){
        var uri = "{{STATIC_URL}}teste.xml";
        function complete(id, o, args) {
            var data = o.responseXML; // Response data.
            var dataObject = {
                        phyloxml: data,
                        fileSource: true
                    };      
            phylocanvas = new Smits.PhyloCanvas(
                dataObject,
                'svgCanvas', 
                800, 800,
                'circular'
                             
            );
            init(); //unitip
        };
        Y.on('io:complete', complete, Y);
        var request = Y.io(uri);
    });
};
	</script>

{% endblock %}

{% block nome %}
		

    <!--<div id="info_align">
        <header><p style="font-size:20px; color:green;">Apresentação Alinhamento</p></br></header>
    
        <div id="alinhamento">
        <pre style="margin-top:40px;margin-left:37px;">{{teste}}</pre>
        <h5><a href="{{ sequencia.arquivo.url }}" style="color:blue; margin-left:37px;">(download)</a></h5>
        </div>
        
        
    </div>-->

{% endblock %}

{% block contato %}
	<div id="svgCanvas"> </div>

{% endblock %}

templates/alinhamento/blast.html
{% extends 'busca/resul_planta.html' %}

{% block nome %}
	<p style="font-size:20px; color:green;">Blast</p>	
{% endblock %}

{%block contato%}
<div id="pagina_conteudo">

	<form method="POST">	
		{% csrf_token %}
		{% for campo in motifs %}
			<div class="fieldWrapper">
				{% if campo.errors%}
					<div style="width:170px; height:20px; list-style:none;font-size:11.5px;" class="notice error">{{ campo.errors }}</div>		
				{% endif %}	
				{{ campo.label_tag }}:</br>
				{{ campo }}
			</div>
		{% endfor %}
		<button type="submit" style="margin-top:10px;">Enviar</button>	
		
		
	</form>
	
</div>
{%endblock%}

templates/alinhamento/blast_result.html
{% extends "busca/resul_seq.html" %}

{% block nome %}
	<p style="font-size:20px; color:green;">Apresentação Blast</p>	
{% endblock %}

{% block contato %}
<div id="perfil_planta2">
		<p style="font-size: 11px;"></p>
	<div id="info_align">
		<header><b>Resultado do Blast</b></br></header>
	
		<div id="alinhamento">
		<pre>{{blast}}</pre>
		</div> 
		<!--<div id="arvore" class="col_3">
			<header><b>Arvore</b></br></header>
			<pre>{% spaceless %}
			{{fasta|linebreaksbr}}
			
			{% endspaceless %}
			</pre>
		</div> -->
		
		
	</div>

</div>



{% endblock %}